<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Shipping.Cli</RootNamespace>
    <AssemblyName>shipping</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shipping.Contracts\Shipping.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Shipping.Cli.Tests" />
  </ItemGroup>

</Project>
